import { db } from '@/db';
import { productVariants } from '@/db/schema';

async function main() {
    const sampleVariants = [
        {
            productId: 4,
            variantName: 'Small',
            sku: 'TSHIRT-IP-001-S',
            price: 499,
            stockQuantity: 15,
            attributes: { size: 'S', chest: '36 inches' },
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            productId: 4,
            variantName: 'Medium',
            sku: 'TSHIRT-IP-001-M',
            price: 499,
            stockQuantity: 20,
            attributes: { size: 'M', chest: '38 inches' },
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            productId: 4,
            variantName: 'Large',
            sku: 'TSHIRT-IP-001-L',
            price: 549,
            stockQuantity: 10,
            attributes: { size: 'L', chest: '40 inches' },
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            productId: 4,
            variantName: 'X-Large',
            sku: 'TSHIRT-IP-001-XL',
            price: 549,
            stockQuantity: 5,
            attributes: { size: 'XL', chest: '42 inches' },
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            productId: 5,
            variantName: 'Small',
            sku: 'TSHIRT-AB-001-S',
            price: 449,
            stockQuantity: 12,
            attributes: { size: 'S', chest: '36 inches' },
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            productId: 5,
            variantName: 'Medium',
            sku: 'TSHIRT-AB-001-M',
            price: 449,
            stockQuantity: 15,
            attributes: { size: 'M', chest: '38 inches' },
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            productId: 5,
            variantName: 'Large',
            sku: 'TSHIRT-AB-001-L',
            price: 499,
            stockQuantity: 8,
            attributes: { size: 'L', chest: '40 inches' },
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            productId: 5,
            variantName: 'X-Large',
            sku: 'TSHIRT-AB-001-XL',
            price: 499,
            stockQuantity: 5,
            attributes: { size: 'XL', chest: '42 inches' },
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            productId: 6,
            variantName: 'Small',
            sku: 'TSHIRT-MQ-001-S',
            price: 399,
            stockQuantity: 13,
            attributes: { size: 'S', chest: '36 inches' },
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            productId: 6,
            variantName: 'Medium',
            sku: 'TSHIRT-MQ-001-M',
            price: 399,
            stockQuantity: 18,
            attributes: { size: 'M', chest: '38 inches' },
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            productId: 6,
            variantName: 'Large',
            sku: 'TSHIRT-MQ-001-L',
            price: 449,
            stockQuantity: 9,
            attributes: { size: 'L', chest: '40 inches' },
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            productId: 6,
            variantName: 'X-Large',
            sku: 'TSHIRT-MQ-001-XL',
            price: 449,
            stockQuantity: 5,
            attributes: { size: 'XL', chest: '42 inches' },
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            productId: 7,
            variantName: 'Medium (18x24)',
            sku: 'PAINT-MC-001-M',
            price: 1799,
            stockQuantity: 8,
            attributes: { size: 'Medium', dimensions: '18x24 inches' },
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            productId: 7,
            variantName: 'Large (24x36)',
            sku: 'PAINT-MC-001-L',
            price: 2299,
            stockQuantity: 7,
            attributes: { size: 'Large', dimensions: '24x36 inches' },
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            productId: 10,
            variantName: 'Red',
            sku: 'DECOR-CC-001-RED',
            price: 599,
            stockQuantity: 15,
            attributes: { color: 'Red', pattern: 'Ethnic' },
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            productId: 10,
            variantName: 'Blue',
            sku: 'DECOR-CC-001-BLUE',
            price: 599,
            stockQuantity: 18,
            attributes: { color: 'Blue', pattern: 'Ethnic' },
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            productId: 10,
            variantName: 'Black',
            sku: 'DECOR-CC-001-BLACK',
            price: 649,
            stockQuantity: 12,
            attributes: { color: 'Black', pattern: 'Ethnic' },
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            productId: 10,
            variantName: 'White',
            sku: 'DECOR-CC-001-WHITE',
            price: 599,
            stockQuantity: 5,
            attributes: { color: 'White', pattern: 'Ethnic' },
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
    ];

    await db.insert(productVariants).values(sampleVariants);
    
    console.log('✅ Product variants seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});