import { db } from '@/db';
import { productVariants } from '@/db/schema';

async function main() {
    const sampleProductVariants = [
        // Product 1 (Jute Basket) - Size variants
        {
            productId: 1,
            variantName: 'Small',
            sku: 'JB-001-SM',
            price: 299.00,
            stockQuantity: 50,
            attributes: JSON.stringify({ size: 'Small', dimensions: '8x6 inches' }),
            isActive: true,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            productId: 1,
            variantName: 'Medium',
            sku: 'JB-001-MD',
            price: 399.00,
            stockQuantity: 45,
            attributes: JSON.stringify({ size: 'Medium', dimensions: '10x8 inches' }),
            isActive: true,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            productId: 1,
            variantName: 'Large',
            sku: 'JB-001-LG',
            price: 549.00,
            stockQuantity: 40,
            attributes: JSON.stringify({ size: 'Large', dimensions: '12x10 inches' }),
            isActive: true,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },

        // Product 2 (Clay Diya) - Pack variants
        {
            productId: 2,
            variantName: 'Pack of 12',
            sku: 'CD-002-P12',
            price: 199.00,
            stockQuantity: 60,
            attributes: JSON.stringify({ quantity: '12 pieces', type: 'Traditional' }),
            isActive: true,
            createdAt: new Date('2024-01-11').toISOString(),
            updatedAt: new Date('2024-01-11').toISOString(),
        },
        {
            productId: 2,
            variantName: 'Pack of 24',
            sku: 'CD-002-P24',
            price: 349.00,
            stockQuantity: 55,
            attributes: JSON.stringify({ quantity: '24 pieces', type: 'Traditional' }),
            isActive: true,
            createdAt: new Date('2024-01-11').toISOString(),
            updatedAt: new Date('2024-01-11').toISOString(),
        },

        // Product 3 (Wall Hanging) - Size variants
        {
            productId: 3,
            variantName: 'Medium',
            sku: 'WH-003-MD',
            price: 799.00,
            stockQuantity: 35,
            attributes: JSON.stringify({ size: 'Medium', dimensions: '18x24 inches' }),
            isActive: true,
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            productId: 3,
            variantName: 'Large',
            sku: 'WH-003-LG',
            price: 999.00,
            stockQuantity: 30,
            attributes: JSON.stringify({ size: 'Large', dimensions: '24x36 inches' }),
            isActive: true,
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },

        // Product 4 (Keychain) - Quantity variants
        {
            productId: 4,
            variantName: 'Single',
            sku: 'KC-004-SG',
            price: 149.00,
            stockQuantity: 70,
            attributes: JSON.stringify({ quantity: '1 piece', material: 'Handcrafted' }),
            isActive: true,
            createdAt: new Date('2024-01-13').toISOString(),
            updatedAt: new Date('2024-01-13').toISOString(),
        },
        {
            productId: 4,
            variantName: 'Pack of 3',
            sku: 'KC-004-P3',
            price: 399.00,
            stockQuantity: 50,
            attributes: JSON.stringify({ quantity: '3 pieces', material: 'Handcrafted' }),
            isActive: true,
            createdAt: new Date('2024-01-13').toISOString(),
            updatedAt: new Date('2024-01-13').toISOString(),
        },

        // Product 5 (T-Shirt) - Size and color variants
        {
            productId: 5,
            variantName: 'Small Red',
            sku: 'TS-005-SM-RED',
            price: 499.00,
            stockQuantity: 45,
            attributes: JSON.stringify({ size: 'S', color: 'Red', fabric: 'Cotton' }),
            isActive: true,
            createdAt: new Date('2024-01-14').toISOString(),
            updatedAt: new Date('2024-01-14').toISOString(),
        },
        {
            productId: 5,
            variantName: 'Medium Blue',
            sku: 'TS-005-MD-BLUE',
            price: 499.00,
            stockQuantity: 50,
            attributes: JSON.stringify({ size: 'M', color: 'Blue', fabric: 'Cotton' }),
            isActive: true,
            createdAt: new Date('2024-01-14').toISOString(),
            updatedAt: new Date('2024-01-14').toISOString(),
        },
        {
            productId: 5,
            variantName: 'Large Black',
            sku: 'TS-005-LG-BLACK',
            price: 549.00,
            stockQuantity: 40,
            attributes: JSON.stringify({ size: 'L', color: 'Black', fabric: 'Cotton' }),
            isActive: true,
            createdAt: new Date('2024-01-14').toISOString(),
            updatedAt: new Date('2024-01-14').toISOString(),
        },

        // Product 6 (T-Shirt) - Size and color variants
        {
            productId: 6,
            variantName: 'Small White',
            sku: 'TS-006-SM-WHITE',
            price: 499.00,
            stockQuantity: 48,
            attributes: JSON.stringify({ size: 'S', color: 'White', fabric: 'Cotton' }),
            isActive: true,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            productId: 6,
            variantName: 'Medium Green',
            sku: 'TS-006-MD-GREEN',
            price: 499.00,
            stockQuantity: 52,
            attributes: JSON.stringify({ size: 'M', color: 'Green', fabric: 'Cotton' }),
            isActive: true,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            productId: 6,
            variantName: 'Large Red',
            sku: 'TS-006-LG-RED',
            price: 549.00,
            stockQuantity: 42,
            attributes: JSON.stringify({ size: 'L', color: 'Red', fabric: 'Cotton' }),
            isActive: true,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },

        // Product 7 (T-Shirt) - Size and color variants
        {
            productId: 7,
            variantName: 'Small Black',
            sku: 'TS-007-SM-BLACK',
            price: 499.00,
            stockQuantity: 46,
            attributes: JSON.stringify({ size: 'S', color: 'Black', fabric: 'Cotton' }),
            isActive: true,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            productId: 7,
            variantName: 'Medium White',
            sku: 'TS-007-MD-WHITE',
            price: 499.00,
            stockQuantity: 54,
            attributes: JSON.stringify({ size: 'M', color: 'White', fabric: 'Cotton' }),
            isActive: true,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            productId: 7,
            variantName: 'Large Blue',
            sku: 'TS-007-LG-BLUE',
            price: 549.00,
            stockQuantity: 38,
            attributes: JSON.stringify({ size: 'L', color: 'Blue', fabric: 'Cotton' }),
            isActive: true,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },

        // Product 8 (T-Shirt) - Size and color variants
        {
            productId: 8,
            variantName: 'Small Green',
            sku: 'TS-008-SM-GREEN',
            price: 499.00,
            stockQuantity: 44,
            attributes: JSON.stringify({ size: 'S', color: 'Green', fabric: 'Cotton' }),
            isActive: true,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            productId: 8,
            variantName: 'Medium Red',
            sku: 'TS-008-MD-RED',
            price: 499.00,
            stockQuantity: 51,
            attributes: JSON.stringify({ size: 'M', color: 'Red', fabric: 'Cotton' }),
            isActive: true,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            productId: 8,
            variantName: 'Large White',
            sku: 'TS-008-LG-WHITE',
            price: 549.00,
            stockQuantity: 39,
            attributes: JSON.stringify({ size: 'L', color: 'White', fabric: 'Cotton' }),
            isActive: true,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },

        // Product 9 (T-Shirt) - Size and color variants
        {
            productId: 9,
            variantName: 'Small Blue',
            sku: 'TS-009-SM-BLUE',
            price: 499.00,
            stockQuantity: 47,
            attributes: JSON.stringify({ size: 'S', color: 'Blue', fabric: 'Cotton' }),
            isActive: true,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            productId: 9,
            variantName: 'Medium Black',
            sku: 'TS-009-MD-BLACK',
            price: 499.00,
            stockQuantity: 53,
            attributes: JSON.stringify({ size: 'M', color: 'Black', fabric: 'Cotton' }),
            isActive: true,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            productId: 9,
            variantName: 'Large Green',
            sku: 'TS-009-LG-GREEN',
            price: 549.00,
            stockQuantity: 41,
            attributes: JSON.stringify({ size: 'L', color: 'Green', fabric: 'Cotton' }),
            isActive: true,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },

        // Product 10 (Painting) - Size variants
        {
            productId: 10,
            variantName: 'Small (12x16)',
            sku: 'PT-010-SM',
            price: 1299.00,
            stockQuantity: 35,
            attributes: JSON.stringify({ size: 'Small', dimensions: '12x16 inches', frame: 'Included' }),
            isActive: true,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            productId: 10,
            variantName: 'Medium (16x20)',
            sku: 'PT-010-MD',
            price: 1599.00,
            stockQuantity: 32,
            attributes: JSON.stringify({ size: 'Medium', dimensions: '16x20 inches', frame: 'Included' }),
            isActive: true,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            productId: 10,
            variantName: 'Large (20x24)',
            sku: 'PT-010-LG',
            price: 1899.00,
            stockQuantity: 28,
            attributes: JSON.stringify({ size: 'Large', dimensions: '20x24 inches', frame: 'Included' }),
            isActive: true,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },

        // Product 11 (Painting) - Size variants
        {
            productId: 11,
            variantName: 'Medium (16x20)',
            sku: 'PT-011-MD',
            price: 1699.00,
            stockQuantity: 30,
            attributes: JSON.stringify({ size: 'Medium', dimensions: '16x20 inches', frame: 'Included' }),
            isActive: true,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            productId: 11,
            variantName: 'Large (20x24)',
            sku: 'PT-011-LG',
            price: 1999.00,
            stockQuantity: 26,
            attributes: JSON.stringify({ size: 'Large', dimensions: '20x24 inches', frame: 'Included' }),
            isActive: true,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },

        // Product 12 (Painting) - Size variants
        {
            productId: 12,
            variantName: 'Small (12x16)',
            sku: 'PT-012-SM',
            price: 1399.00,
            stockQuantity: 33,
            attributes: JSON.stringify({ size: 'Small', dimensions: '12x16 inches', frame: 'Included' }),
            isActive: true,
            createdAt: new Date('2024-01-21').toISOString(),
            updatedAt: new Date('2024-01-21').toISOString(),
        },
        {
            productId: 12,
            variantName: 'Medium (16x20)',
            sku: 'PT-012-MD',
            price: 1699.00,
            stockQuantity: 29,
            attributes: JSON.stringify({ size: 'Medium', dimensions: '16x20 inches', frame: 'Included' }),
            isActive: true,
            createdAt: new Date('2024-01-21').toISOString(),
            updatedAt: new Date('2024-01-21').toISOString(),
        },

        // Product 13 (Painting) - Size variants
        {
            productId: 13,
            variantName: 'Medium (16x20)',
            sku: 'PT-013-MD',
            price: 1799.00,
            stockQuantity: 31,
            attributes: JSON.stringify({ size: 'Medium', dimensions: '16x20 inches', frame: 'Included' }),
            isActive: true,
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        {
            productId: 13,
            variantName: 'Large (20x24)',
            sku: 'PT-013-LG',
            price: 2099.00,
            stockQuantity: 27,
            attributes: JSON.stringify({ size: 'Large', dimensions: '20x24 inches', frame: 'Included' }),
            isActive: true,
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },

        // Product 14 (Home Decor) - Size variants
        {
            productId: 14,
            variantName: 'Small (6 inch)',
            sku: 'HD-014-SM',
            price: 599.00,
            stockQuantity: 42,
            attributes: JSON.stringify({ size: '6 inch', material: 'Ceramic' }),
            isActive: true,
            createdAt: new Date('2024-01-23').toISOString(),
            updatedAt: new Date('2024-01-23').toISOString(),
        },
        {
            productId: 14,
            variantName: 'Medium (8 inch)',
            sku: 'HD-014-MD',
            price: 749.00,
            stockQuantity: 38,
            attributes: JSON.stringify({ size: '8 inch', material: 'Ceramic' }),
            isActive: true,
            createdAt: new Date('2024-01-23').toISOString(),
            updatedAt: new Date('2024-01-23').toISOString(),
        },
        {
            productId: 14,
            variantName: 'Large (10 inch)',
            sku: 'HD-014-LG',
            price: 899.00,
            stockQuantity: 34,
            attributes: JSON.stringify({ size: '10 inch', material: 'Ceramic' }),
            isActive: true,
            createdAt: new Date('2024-01-23').toISOString(),
            updatedAt: new Date('2024-01-23').toISOString(),
        },

        // Product 15 (Home Decor) - Set variants
        {
            productId: 15,
            variantName: 'Set of 2',
            sku: 'HD-015-S2',
            price: 899.00,
            stockQuantity: 36,
            attributes: JSON.stringify({ quantity: '2 pieces', material: 'Wood' }),
            isActive: true,
            createdAt: new Date('2024-01-24').toISOString(),
            updatedAt: new Date('2024-01-24').toISOString(),
        },
        {
            productId: 15,
            variantName: 'Set of 4',
            sku: 'HD-015-S4',
            price: 1599.00,
            stockQuantity: 32,
            attributes: JSON.stringify({ quantity: '4 pieces', material: 'Wood' }),
            isActive: true,
            createdAt: new Date('2024-01-24').toISOString(),
            updatedAt: new Date('2024-01-24').toISOString(),
        },

        // Product 16 (Home Decor) - Quantity variants
        {
            productId: 16,
            variantName: 'Single',
            sku: 'HD-016-SG',
            price: 699.00,
            stockQuantity: 40,
            attributes: JSON.stringify({ quantity: '1 piece', finish: 'Matte' }),
            isActive: true,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            productId: 16,
            variantName: 'Set of 3',
            sku: 'HD-016-S3',
            price: 1899.00,
            stockQuantity: 35,
            attributes: JSON.stringify({ quantity: '3 pieces', finish: 'Matte' }),
            isActive: true,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },

        // Product 17 (Home Decor) - Size variants
        {
            productId: 17,
            variantName: 'Medium',
            sku: 'HD-017-MD',
            price: 1199.00,
            stockQuantity: 33,
            attributes: JSON.stringify({ size: 'Medium', dimensions: '14x18 inches' }),
            isActive: true,
            createdAt: new Date('2024-01-26').toISOString(),
            updatedAt: new Date('2024-01-26').toISOString(),
        },
        {
            productId: 17,
            variantName: 'Large',
            sku: 'HD-017-LG',
            price: 1499.00,
            stockQuantity: 29,
            attributes: JSON.stringify({ size: 'Large', dimensions: '18x24 inches' }),
            isActive: true,
            createdAt: new Date('2024-01-26').toISOString(),
            updatedAt: new Date('2024-01-26').toISOString(),
        },

        // Product 18 (Home Decor) - Size variants
        {
            productId: 18,
            variantName: 'Small',
            sku: 'HD-018-SM',
            price: 799.00,
            stockQuantity: 43,
            attributes: JSON.stringify({ size: 'Small', height: '10 inches' }),
            isActive: true,
            createdAt: new Date('2024-01-27').toISOString(),
            updatedAt: new Date('2024-01-27').toISOString(),
        },
        {
            productId: 18,
            variantName: 'Medium',
            sku: 'HD-018-MD',
            price: 999.00,
            stockQuantity: 39,
            attributes: JSON.stringify({ size: 'Medium', height: '14 inches' }),
            isActive: true,
            createdAt: new Date('2024-01-27').toISOString(),
            updatedAt: new Date('2024-01-27').toISOString(),
        },
        {
            productId: 18,
            variantName: 'Large',
            sku: 'HD-018-LG',
            price: 1199.00,
            stockQuantity: 35,
            attributes: JSON.stringify({ size: 'Large', height: '18 inches' }),
            isActive: true,
            createdAt: new Date('2024-01-27').toISOString(),
            updatedAt: new Date('2024-01-27').toISOString(),
        },

        // Product 19 (Festive) - Size variants
        {
            productId: 19,
            variantName: 'Small',
            sku: 'FT-019-SM',
            price: 899.00,
            stockQuantity: 44,
            attributes: JSON.stringify({ size: 'Small', length: '15 feet' }),
            isActive: true,
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            productId: 19,
            variantName: 'Large',
            sku: 'FT-019-LG',
            price: 1299.00,
            stockQuantity: 38,
            attributes: JSON.stringify({ size: 'Large', length: '30 feet' }),
            isActive: true,
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },

        // Product 20 (Festive) - Kit variants
        {
            productId: 20,
            variantName: 'Basic Kit',
            sku: 'FT-020-BASIC',
            price: 1499.00,
            stockQuantity: 36,
            attributes: JSON.stringify({ type: 'Basic Kit', items: '10 pieces' }),
            isActive: true,
            createdAt: new Date('2024-01-29').toISOString(),
            updatedAt: new Date('2024-01-29').toISOString(),
        },
        {
            productId: 20,
            variantName: 'Premium Kit',
            sku: 'FT-020-PREMIUM',
            price: 2299.00,
            stockQuantity: 31,
            attributes: JSON.stringify({ type: 'Premium Kit', items: '20 pieces' }),
            isActive: true,
            createdAt: new Date('2024-01-29').toISOString(),
            updatedAt: new Date('2024-01-29').toISOString(),
        },

        // Product 21 (Festive) - Size variants
        {
            productId: 21,
            variantName: 'Small',
            sku: 'FT-021-SM',
            price: 699.00,
            stockQuantity: 45,
            attributes: JSON.stringify({ size: 'Small', dimensions: '12 inches' }),
            isActive: true,
            createdAt: new Date('2024-01-30').toISOString(),
            updatedAt: new Date('2024-01-30').toISOString(),
        },
        {
            productId: 21,
            variantName: 'Medium',
            sku: 'FT-021-MD',
            price: 899.00,
            stockQuantity: 41,
            attributes: JSON.stringify({ size: 'Medium', dimensions: '18 inches' }),
            isActive: true,
            createdAt: new Date('2024-01-30').toISOString(),
            updatedAt: new Date('2024-01-30').toISOString(),
        },
        {
            productId: 21,
            variantName: 'Large',
            sku: 'FT-021-LG',
            price: 1099.00,
            stockQuantity: 37,
            attributes: JSON.stringify({ size: 'Large', dimensions: '24 inches' }),
            isActive: true,
            createdAt: new Date('2024-01-30').toISOString(),
            updatedAt: new Date('2024-01-30').toISOString(),
        },
    ];

    await db.insert(productVariants).values(sampleProductVariants);
    
    console.log('✅ Product variants seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});