import { db } from '@/db';
import { products } from '@/db/schema';

async function main() {
    const sampleProducts = [
        {
            name: 'Handmade Greeting Cards Set',
            slug: 'handmade-greeting-cards',
            description: 'Set of 5 beautiful handcrafted greeting cards for any occasion',
            basePrice: 299,
            categoryId: 1,
            sku: 'GIFT-GC-001',
            stockQuantity: 45,
            isActive: true,
            featured: false,
            images: ['/images/products/greeting-cards-1.jpg', '/images/products/greeting-cards-2.jpg'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Premium Gift Hamper',
            slug: 'premium-gift-hamper',
            description: 'Luxury gift hamper with assorted handmade items perfect for gifting',
            basePrice: 1499,
            categoryId: 1,
            sku: 'GIFT-HM-001',
            stockQuantity: 20,
            isActive: true,
            featured: true,
            images: ['/images/products/gift-hamper-1.jpg', '/images/products/gift-hamper-2.jpg'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Custom Photo Frame',
            slug: 'custom-photo-frame',
            description: 'Elegant wooden photo frame with custom engraving option',
            basePrice: 599,
            categoryId: 1,
            sku: 'GIFT-FR-001',
            stockQuantity: 35,
            isActive: true,
            featured: false,
            images: ['/images/products/photo-frame-1.jpg'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Indian Pride Graphic Tee',
            slug: 'indian-pride-tee',
            description: 'Premium cotton t-shirt with vibrant Indian cultural print',
            basePrice: 499,
            categoryId: 2,
            sku: 'TSHIRT-IP-001',
            stockQuantity: 50,
            isActive: true,
            featured: true,
            images: ['/images/products/tshirt-indian-1.jpg', '/images/products/tshirt-indian-2.jpg'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Abstract Art Print Tee',
            slug: 'abstract-art-tee',
            description: 'Stylish t-shirt with unique abstract art design',
            basePrice: 449,
            categoryId: 2,
            sku: 'TSHIRT-AB-001',
            stockQuantity: 40,
            isActive: true,
            featured: false,
            images: ['/images/products/tshirt-abstract-1.jpg'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Minimalist Quote Tee',
            slug: 'minimalist-quote-tee',
            description: 'Clean design t-shirt with inspirational quote',
            basePrice: 399,
            categoryId: 2,
            sku: 'TSHIRT-MQ-001',
            stockQuantity: 45,
            isActive: true,
            featured: false,
            images: ['/images/products/tshirt-quote-1.jpg'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Modern Canvas Wall Art',
            slug: 'modern-canvas-art',
            description: 'Contemporary abstract painting on premium canvas',
            basePrice: 1799,
            categoryId: 3,
            sku: 'PAINT-MC-001',
            stockQuantity: 15,
            isActive: true,
            featured: true,
            images: ['/images/products/canvas-modern-1.jpg', '/images/products/canvas-modern-2.jpg'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Nature Landscape Painting',
            slug: 'nature-landscape-painting',
            description: 'Serene nature landscape artwork perfect for living rooms',
            basePrice: 1299,
            categoryId: 3,
            sku: 'PAINT-NL-001',
            stockQuantity: 18,
            isActive: true,
            featured: false,
            images: ['/images/products/landscape-1.jpg'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Traditional Indian Art',
            slug: 'traditional-indian-art',
            description: 'Beautiful traditional Indian painting with intricate details',
            basePrice: 2199,
            categoryId: 3,
            sku: 'PAINT-TI-001',
            stockQuantity: 10,
            isActive: true,
            featured: false,
            images: ['/images/products/traditional-art-1.jpg'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Decorative Cushion Covers',
            slug: 'decorative-cushion-covers',
            description: 'Set of 2 premium cushion covers with ethnic prints',
            basePrice: 599,
            categoryId: 4,
            sku: 'DECOR-CC-001',
            stockQuantity: 50,
            isActive: true,
            featured: false,
            images: ['/images/products/cushion-covers-1.jpg', '/images/products/cushion-covers-2.jpg'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Macrame Wall Hanging',
            slug: 'macrame-wall-hanging',
            description: 'Handcrafted macrame wall decor piece',
            basePrice: 899,
            categoryId: 4,
            sku: 'DECOR-MH-001',
            stockQuantity: 25,
            isActive: true,
            featured: true,
            images: ['/images/products/macrame-1.jpg'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Ceramic Decorative Vase',
            slug: 'ceramic-vase',
            description: 'Elegant handmade ceramic vase for home decoration',
            basePrice: 799,
            categoryId: 4,
            sku: 'DECOR-CV-001',
            stockQuantity: 30,
            isActive: true,
            featured: false,
            images: ['/images/products/ceramic-vase-1.jpg'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        }
    ];

    await db.insert(products).values(sampleProducts);
    
    console.log('✅ Products seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});