import { db } from '@/db';
import { products } from '@/db/schema';

async function main() {
    const sampleProducts = [
        {
            name: 'Handwoven Jute Basket',
            slug: 'handwoven-jute-basket',
            description: 'Beautiful handwoven jute basket perfect for organizing or gifting',
            basePrice: 349,
            categoryId: 1,
            sku: 'HG001',
            stockQuantity: 50,
            isActive: true,
            featured: true,
            images: ['/images/products/jute-basket-1.jpg', '/images/products/jute-basket-2.jpg'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Clay Diya Set of 12',
            slug: 'clay-diya-set',
            description: 'Traditional handmade clay diyas for festivals and celebrations',
            basePrice: 199,
            categoryId: 1,
            sku: 'HG002',
            stockQuantity: 100,
            isActive: true,
            featured: false,
            images: ['/images/products/diya-set-1.jpg'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Embroidered Wall Hanging',
            slug: 'embroidered-wall-hanging',
            description: 'Colorful hand-embroidered wall hanging with ethnic patterns',
            basePrice: 899,
            categoryId: 1,
            sku: 'HG003',
            stockQuantity: 30,
            isActive: true,
            featured: true,
            images: ['/images/products/wall-hanging-1.jpg', '/images/products/wall-hanging-2.jpg'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Handcrafted Wooden Keychain',
            slug: 'wooden-keychain',
            description: 'Carved wooden keychain with intricate designs',
            basePrice: 149,
            categoryId: 1,
            sku: 'HG004',
            stockQuantity: 200,
            isActive: true,
            featured: false,
            images: ['/images/products/keychain-1.jpg'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Bharat Pride T-Shirt',
            slug: 'bharat-pride-tshirt',
            description: 'Premium cotton t-shirt with India pride print',
            basePrice: 499,
            categoryId: 2,
            sku: 'TS001',
            stockQuantity: 150,
            isActive: true,
            featured: true,
            images: ['/images/products/bharat-tshirt-1.jpg', '/images/products/bharat-tshirt-2.jpg'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Mandala Art T-Shirt',
            slug: 'mandala-art-tshirt',
            description: 'Artistic mandala print on soft cotton fabric',
            basePrice: 549,
            categoryId: 2,
            sku: 'TS002',
            stockQuantity: 120,
            isActive: true,
            featured: false,
            images: ['/images/products/mandala-tshirt-1.jpg'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Bollywood Swag T-Shirt',
            slug: 'bollywood-swag-tshirt',
            description: 'Trendy Bollywood inspired graphic t-shirt',
            basePrice: 599,
            categoryId: 2,
            sku: 'TS003',
            stockQuantity: 100,
            isActive: true,
            featured: true,
            images: ['/images/products/bollywood-tshirt-1.jpg', '/images/products/bollywood-tshirt-2.jpg'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Yoga Vibes T-Shirt',
            slug: 'yoga-vibes-tshirt',
            description: 'Comfortable t-shirt with peaceful yoga graphics',
            basePrice: 529,
            categoryId: 2,
            sku: 'TS004',
            stockQuantity: 80,
            isActive: true,
            featured: false,
            images: ['/images/products/yoga-tshirt-1.jpg'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Desi Swag T-Shirt',
            slug: 'desi-swag-tshirt',
            description: 'Bold desi slogan printed on premium fabric',
            basePrice: 579,
            categoryId: 2,
            sku: 'TS005',
            stockQuantity: 90,
            isActive: true,
            featured: false,
            images: ['/images/products/desi-tshirt-1.jpg'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Radha Krishna Canvas',
            slug: 'radha-krishna-canvas',
            description: 'Beautiful Radha Krishna painting on canvas',
            basePrice: 1499,
            categoryId: 3,
            sku: 'PT001',
            stockQuantity: 25,
            isActive: true,
            featured: true,
            images: ['/images/products/radha-krishna-1.jpg', '/images/products/radha-krishna-2.jpg'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Abstract Mountain Landscape',
            slug: 'abstract-mountain-landscape',
            description: 'Modern abstract painting of mountain landscape',
            basePrice: 1799,
            categoryId: 3,
            sku: 'PT002',
            stockQuantity: 20,
            isActive: true,
            featured: false,
            images: ['/images/products/mountain-painting-1.jpg'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Peacock Feather Art',
            slug: 'peacock-feather-art',
            description: 'Vibrant peacock feather artwork with colors',
            basePrice: 1299,
            categoryId: 3,
            sku: 'PT003',
            stockQuantity: 30,
            isActive: true,
            featured: true,
            images: ['/images/products/peacock-art-1.jpg', '/images/products/peacock-art-2.jpg'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Sunset Beach Painting',
            slug: 'sunset-beach-painting',
            description: 'Serene sunset beach scene painting',
            basePrice: 1599,
            categoryId: 3,
            sku: 'PT004',
            stockQuantity: 18,
            isActive: true,
            featured: false,
            images: ['/images/products/sunset-painting-1.jpg'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Brass Ganesha Statue',
            slug: 'brass-ganesha-statue',
            description: 'Handcrafted brass Ganesha idol for home temple',
            basePrice: 799,
            categoryId: 4,
            sku: 'HD001',
            stockQuantity: 60,
            isActive: true,
            featured: true,
            images: ['/images/products/ganesha-statue-1.jpg', '/images/products/ganesha-statue-2.jpg'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Decorative Cushion Cover Set',
            slug: 'decorative-cushion-cover',
            description: 'Set of 2 ethnic print cushion covers',
            basePrice: 399,
            categoryId: 4,
            sku: 'HD002',
            stockQuantity: 80,
            isActive: true,
            featured: false,
            images: ['/images/products/cushion-cover-1.jpg'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Marble Tea Light Holder',
            slug: 'marble-tea-light-holder',
            description: 'Elegant marble tea light candle holder',
            basePrice: 599,
            categoryId: 4,
            sku: 'HD003',
            stockQuantity: 70,
            isActive: true,
            featured: true,
            images: ['/images/products/tea-light-holder-1.jpg', '/images/products/tea-light-holder-2.jpg'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Wooden Wall Clock',
            slug: 'wooden-wall-clock',
            description: 'Stylish wooden wall clock with Roman numerals',
            basePrice: 1299,
            categoryId: 4,
            sku: 'HD004',
            stockQuantity: 40,
            isActive: true,
            featured: false,
            images: ['/images/products/wall-clock-1.jpg'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Macrame Plant Hanger',
            slug: 'macrame-plant-hanger',
            description: 'Handmade macrame plant hanger for indoor plants',
            basePrice: 449,
            categoryId: 4,
            sku: 'HD005',
            stockQuantity: 55,
            isActive: true,
            featured: false,
            images: ['/images/products/plant-hanger-1.jpg'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Diwali Decorative Toran',
            slug: 'diwali-toran',
            description: 'Traditional decorative door hanging toran for Diwali',
            basePrice: 299,
            categoryId: 5,
            sku: 'FC001',
            stockQuantity: 150,
            isActive: true,
            featured: true,
            images: ['/images/products/diwali-toran-1.jpg', '/images/products/diwali-toran-2.jpg'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Rangoli Stencil Kit',
            slug: 'rangoli-stencil-kit',
            description: 'Complete rangoli stencil kit with 10 designs',
            basePrice: 249,
            categoryId: 5,
            sku: 'FC002',
            stockQuantity: 120,
            isActive: true,
            featured: false,
            images: ['/images/products/rangoli-kit-1.jpg'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Festive Gift Hamper Box',
            slug: 'festive-gift-hamper',
            description: 'Decorative gift hamper box for festive gifting',
            basePrice: 399,
            categoryId: 5,
            sku: 'FC003',
            stockQuantity: 80,
            isActive: true,
            featured: true,
            images: ['/images/products/gift-hamper-1.jpg', '/images/products/gift-hamper-2.jpg'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
    ];

    await db.insert(products).values(sampleProducts);
    
    console.log('✅ Products seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});