import { db } from '@/db';
import { shippingRules } from '@/db/schema';

async function main() {
    const currentTimestamp = new Date().toISOString();
    
    const sampleShippingRules = [
        {
            pincodeStart: '110001',
            pincodeEnd: '110096',
            state: 'Delhi',
            deliveryDays: 2,
            shippingCharge: 50,
            isCodAvailable: true,
            isActive: true,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            pincodeStart: '110097',
            pincodeEnd: '110099',
            state: 'Delhi',
            deliveryDays: 3,
            shippingCharge: 50,
            isCodAvailable: true,
            isActive: true,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            pincodeStart: '122001',
            pincodeEnd: '122050',
            state: 'Haryana',
            deliveryDays: 3,
            shippingCharge: 60,
            isCodAvailable: true,
            isActive: true,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            pincodeStart: '201301',
            pincodeEnd: '201320',
            state: 'Uttar Pradesh',
            deliveryDays: 3,
            shippingCharge: 60,
            isCodAvailable: true,
            isActive: true,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            pincodeStart: '400001',
            pincodeEnd: '400050',
            state: 'Maharashtra',
            deliveryDays: 3,
            shippingCharge: 60,
            isCodAvailable: true,
            isActive: true,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            pincodeStart: '400051',
            pincodeEnd: '400104',
            state: 'Maharashtra',
            deliveryDays: 4,
            shippingCharge: 60,
            isCodAvailable: true,
            isActive: true,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            pincodeStart: '560001',
            pincodeEnd: '560050',
            state: 'Karnataka',
            deliveryDays: 3,
            shippingCharge: 60,
            isCodAvailable: true,
            isActive: true,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            pincodeStart: '560051',
            pincodeEnd: '560100',
            state: 'Karnataka',
            deliveryDays: 4,
            shippingCharge: 60,
            isCodAvailable: true,
            isActive: true,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            pincodeStart: '600001',
            pincodeEnd: '600120',
            state: 'Tamil Nadu',
            deliveryDays: 4,
            shippingCharge: 70,
            isCodAvailable: true,
            isActive: true,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            pincodeStart: '500001',
            pincodeEnd: '500100',
            state: 'Telangana',
            deliveryDays: 4,
            shippingCharge: 70,
            isCodAvailable: true,
            isActive: true,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            pincodeStart: '411001',
            pincodeEnd: '411060',
            state: 'Maharashtra',
            deliveryDays: 4,
            shippingCharge: 70,
            isCodAvailable: true,
            isActive: true,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            pincodeStart: '700001',
            pincodeEnd: '700150',
            state: 'West Bengal',
            deliveryDays: 5,
            shippingCharge: 80,
            isCodAvailable: true,
            isActive: true,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            pincodeStart: '380001',
            pincodeEnd: '380060',
            state: 'Gujarat',
            deliveryDays: 5,
            shippingCharge: 80,
            isCodAvailable: true,
            isActive: true,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            pincodeStart: '302001',
            pincodeEnd: '302040',
            state: 'Rajasthan',
            deliveryDays: 5,
            shippingCharge: 80,
            isCodAvailable: true,
            isActive: true,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            pincodeStart: '160001',
            pincodeEnd: '160050',
            state: 'Chandigarh',
            deliveryDays: 4,
            shippingCharge: 70,
            isCodAvailable: true,
            isActive: true,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            pincodeStart: '600121',
            pincodeEnd: '799999',
            state: 'Other',
            deliveryDays: 7,
            shippingCharge: 100,
            isCodAvailable: true,
            isActive: true,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
    ];

    await db.insert(shippingRules).values(sampleShippingRules);
    
    console.log('✅ Shipping rules seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});